name = "syncts"
main = "index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "syncts"
database_id = "81c5eb43-213a-434c-81d5-a2c1d3a19e9d"
